Repository jenkins-x/jx-pipelines-visualizer, pull requests merged in 2020-12, with the labels that each got.

#40 fix: fix ingress & tls syntax #39
  charts/jx-pipelines-visualizer/templates/ingress.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, ok-to-test, size/M

#44 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/XL, updatebot

#43 refactor: remove old v2 requirements
  cmd/server/main.go
  go.mod
  go.sum
  informer.go
  pipeline.go
  web/handlers/functions/pipeline.go
  web/handlers/logs.go
  web/handlers/logs_live.go
  web/handlers/pipeline.go
  web/handlers/pipelinerun.go
  web/handlers/router.go
Labels: approved, lgtm, size/L

#45 fix: mount git creds so we can clone requirements from private git repos
  charts/jx-pipelines-visualizer/templates/deployment.yaml
  go.mod
  go.sum
Labels: approved, size/S

#47 fix: update jenkins-x (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (95923d9093f49b0abc4cb65cbb0933af8f48e040) to master (c299962020e644b698090e61d43169e5c26720bf)
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: approved, size/XS

#46 chore: make git secret name configurable so we can use jx v2 and v3 git secret names
  charts/jx-pipelines-visualizer/templates/deployment.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, size/XS

#48 chore: ugprade pipeline
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M

#49 fix: upgrade to latest pipeline
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS
