Repository jenkins-x/jx-pipelines-visualizer, pull requests merged in 2020-10, with the labels that each got.

#5 fix: add an OWNERS file
  OWNERS
Labels: lgtm, size/S

#6 fix: avoid failing if less than 3 pipelines
  store.go
  web/templates/home.tmpl
Labels: approved, size/S

#8 fix: add a tekton dashboard style path for PipelineRuns
  go.mod
  go.sum
  web/handlers/pipelinerun.go
  web/handlers/router.go
Labels: approved, size/L

#9 fix: various small fixes
  .goreleaser.yml
  Dockerfile
  charts/jx-pipelines-visualizer/values.yaml
  cmd/server/main.go
  hack/changelog-header.md
Labels: approved, size/S

#10 fix: add breadcrumb links
  web/templates/pipeline.tmpl
Labels: approved, size/XS

#11 fix: add installation instructions in the readme
  README.md
Labels: approved, size/M

#12 fix: Add a default avatar + add a font-size for title
  web/static/app.css
  web/static/avatar.png
  web/templates/home.tmpl
  web/templates/owner.tmpl
  web/templates/pipeline.tmpl
Labels: approved, ok-to-test, size/M

#13 perf: Improve logs performance
  web/static/app.css
  web/templates/pipeline.tmpl
Labels: approved, ok-to-test, size/S

#14 fix: allow annotations to be added to the ServiceAccount
  charts/jx-pipelines-visualizer/templates/rbac.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, size/XS

#19 fix: switch to tekton PipelineRun CI/CD
  .lighthouse/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  jenkins-x.yml
Labels: size/XL

#18 fix: add host to tls secret
  charts/jx-pipelines-visualizer/templates/ingress.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#22 fix: upgrade dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#23 feat: Improve pipeline view
  web/static/app.css
  web/static/pipeline/index.js
  web/static/pipeline/main.css
  web/templates/pipeline.tmpl
Labels: approved, enhancement, size/L

#25 feat: Add color switch theme for logs
  web/static/app.css
  web/static/pipeline/index.js
  web/static/pipeline/main.css
  web/templates/pipeline.tmpl
Labels: approved, enhancement, size/L

#26 fix: Break word to avoid scrolling on x axis
  web/static/pipeline/main.css
Labels: approved, size/XS

#27 docs: a minor tweak to the v2 install instructions
  README.md
Labels: approved, ok-to-test, size/S

#33 fix: repos with dots are now supported
  web/handlers/router.go
Labels: approved, size/M

#35 feat: improve pipelines listing
  store.go
  web/handlers/branch.go
  web/handlers/functions/reflect.go
  web/handlers/owner.go
  web/handlers/repository.go
  web/handlers/router.go
  web/static/branch/index.js
  web/templates/branch.tmpl
  web/templates/home.tmpl
  web/templates/owner.tmpl
  web/templates/repository.tmpl
Labels: approved, size/L
