Repository jenkins-x/jx-pipelines-visualizer, pull requests merged in 2021-01, with the labels that each got.

#53 feat: istio toggle to create virtualservice for provided gateway
  charts/jx-pipelines-visualizer/templates/istio.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#56 feat: Update archived_logs and put new buttons to view and download raw logs
  web/static/archived_logs/index.js
  web/static/lib/ansi_up.js
  web/static/lib/ansi_up.js.map
  web/static/lib/clr-icons.min.css
  web/static/lib/clr-icons.min.js
  web/static/lib/clr-ui.min.css
  web/static/lib/custom-elements.min.js
  web/static/pipeline/index.js
  web/static/pipeline/main.css
  web/templates/archived_logs.tmpl
  web/templates/layout.tmpl
  web/templates/pipeline.tmpl
Labels: approved, size/L

#57 fix: bad path in archived_logs
  web/templates/archived_logs.tmpl
Labels: approved, size/XS

#58 docs: update instructions for jx v2
  README.md
Labels: approved, size/XS

#59 fix: allow urls with or without final slash
  web/handlers/router.go
Labels: approved, size/XS

#60 feat: add direct links to repo, pr/branch, author
  pipeline.go
  store.go
  web/handlers/functions/links.go
  web/handlers/router.go
  web/templates/home.tmpl
Labels: approved, size/L

#61 fix: always set a start time for pipelines
  pipeline.go
Labels: approved, size/XS

#62 feat: display the number of pipelines for each status
  store.go
  web/static/app.css
  web/static/home/index.js
  web/templates/home.tmpl
Labels: approved, size/M

#63 feat: display the pipeline description in the list
  pipeline.go
  store.go
  web/templates/home.tmpl
Labels: approved, size/XS

#64 feat: display cards on the homepage
  informer.go
  store.go
  web/handlers/branch.go
  web/handlers/functions/pipeline_counts.go
  web/handlers/home.go
  web/handlers/owner.go
  web/handlers/repository.go
  web/handlers/router.go
  web/static/app.css
  web/static/home/index.js
  web/templates/home.tmpl
Labels: approved, size/L

#65 feat: display pipeline steps
  web/static/app.css
  web/static/favicon-16x16.png
  web/static/favicon-32x32.png
  web/static/favicon.ico
  web/static/jenkins-x.svg
  web/static/pipeline/index.js
  web/static/pipeline/main.css
  web/templates/archived_logs.tmpl
  web/templates/home.tmpl
  web/templates/layout.tmpl
  web/templates/pipeline.tmpl
Labels: approved, size/L

#66 feat: read pipelines from long-term storage
  charts/jx-pipelines-visualizer/templates/deployment.yaml
  charts/jx-pipelines-visualizer/values.yaml
  cmd/server/main.go
  go.mod
  go.sum
  web/handlers/pipeline.go
  web/handlers/router.go
  web/static/pipeline/index.js
  web/templates/pipeline.tmpl
Labels: approved, size/L

#67 fix: don't cache static resources between releases
  Makefile
  cmd/server/main.go
  internal/version/version.go
  store.go
  web/handlers/functions/app.go
  web/handlers/router.go
  web/templates/archived_logs.tmpl
  web/templates/home.tmpl
  web/templates/layout.tmpl
  web/templates/pipeline.tmpl
Labels: approved, size/M

#68 feat: improve the pipeline UI
  go.mod
  go.sum
  web/handlers/functions/links.go
  web/handlers/pipeline.go
  web/handlers/router.go
  web/static/pipeline/main.css
  web/templates/pipeline.tmpl
Labels: approved, size/L

#70 chore: dep bump
  go.mod
  go.sum
Labels: approved, ok-to-test, size/L

#71 feat: display the preview env URL when available
  .goreleaser.yml
  web/handlers/functions/pipeline.go
  web/handlers/router.go
  web/templates/pipeline.tmpl
Labels: approved

#69 fix: pipelinerun handler should fail cleanly
  web/handlers/pipelinerun.go
  web/handlers/router.go
Labels: approved, lgtm, size/M

#72 feat: Collapse steps
  go.mod
  go.sum
  web/static/app.css
  web/static/pipeline/index.js
  web/static/pipeline/main.css
  web/templates/archived_logs.tmpl
  web/templates/pipeline.tmpl
Labels: approved, size/XL

#75 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/L, updatebot

#76 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#78 fix: filter for pipelines managed by static jenkins
  informer.go
  pipeline.go
Labels: approved

#79 chore: improve readme and add screenshots
  README.md
  docs/screenshots/home.png
  docs/screenshots/pipeline-success-with-timeline.png
  docs/screenshots/pipeline-success.png
Labels: approved, size/M

#80 fix: error msg was not displayed
  web/static/pipeline/index.js
  web/templates/pipeline.tmpl
Labels: approved, size/S

#81 fix: display the error msg for the archived logs
  web/static/pipeline/index.js
  web/templates/archived_logs.tmpl
Labels: size/S

#83 fix: CSS flexbox bug in safari
  web/static/app.css
Labels: approved, size/XS

#84 chore: add footer with link to github and version
  web/static/app.css
  web/templates/layout.tmpl
Labels: approved, size/S

#85 chore: use semantic releases
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#86 feat: new webpage with all running pipelines/stages/steps
  cmd/server/main.go
  informer.go
  pipeline_running.go
  web/handlers/functions/links.go
  web/handlers/router.go
  web/handlers/running.go
  web/handlers/running_events.go
  web/static/app.css
  web/static/running/index.js
  web/templates/home.tmpl
  web/templates/running.tmpl
Labels: approved, size/L

#87 chore: don't use a release header
  .lighthouse/jenkins-x/release.yaml
  hack/changelog-header.md
Labels: approved, size/S

#88 chore: update pipeline-catalog
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/M

#89 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
