Repository jenkins-x/jx-pipelines-visualizer, pull requests merged in 2021-05, with the labels that each got.

#112 feat: add link to lighthouse trace if available
  web/handlers/functions/links.go
  web/handlers/functions/pipeline.go
  web/handlers/router.go
  web/templates/pipeline.tmpl
Labels: approved, size/M

#115 feat: support pod.envFrom in values, for example to provide minio creds
  charts/jx-pipelines-visualizer/templates/deployment.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#116 fix: Remove login:pass from origin if needed
  web/static/pipeline/index.js
Labels: approved, size/XS

#117 fix(chart): set the ingress class to nginx by default
  charts/jx-pipelines-visualizer/templates/ingress.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, size/S

#118 fix: live logs with meta pipelines
  web/handlers/logs_live.go
Labels: approved, size/M

#119 chore(deps): upgrade jx-pipeline
  go.mod
  go.sum
Labels: approved, size/L

#121 fix: handle v3 issue with live logs
  go.mod
  go.sum
  web/handlers/logs_live.go
Labels: approved, size/M

#122 chore(deps): upgrade jx-pipeline to 0.0.139
  go.mod
  go.sum
Labels: approved, size/XS

#125 fix: support links to gitlab and bitbucket
  web/handlers/functions/links.go
  web/handlers/functions/pipeline.go
  web/handlers/router.go
  web/templates/pipeline.tmpl
Labels: approved, size/L
