Repository jenkins-x/jx-pipelines-visualizer, pull requests merged in 2021-06, with the labels that each got.

#127 fix: javascript error in the pipeline logs
  web/static/pipeline/index.js
Labels: approved, size/S

#128 chore(deps): upgrade jx-pipeline
  go.mod
  go.sum
  web/handlers/pipelinerun.go
Labels: approved, size/M

#129 fix: fix missing RBAC permission
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, size/XS

#131 fix: logs errors should be visible by default
  web/static/pipeline/index.js
Labels: approved, size/XS

#133 feat: add support for s3 compatible buckets
  charts/jx-pipelines-visualizer/templates/deployment.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, ok-to-test, size/S

#134 fix: add support for v1 ingress
  charts/jx-pipelines-visualizer/templates/ingress.yaml
  charts/jx-pipelines-visualizer/values.yaml
Labels: approved, size/S
