Repository jenkins-x/jx-pipelines-visualizer, pull requests merged in 2021-04, with the labels that each got.

#105 feat: open pipeline trace URL
  charts/jx-pipelines-visualizer/templates/deployment.yaml
  charts/jx-pipelines-visualizer/values.yaml
  cmd/server/main.go
  web/handlers/functions/pipeline.go
  web/handlers/router.go
  web/static/pipeline/index.js
  web/templates/pipeline.tmpl
Labels: approved, size/M

#106 fix: only display trace link if there is a trace
  web/templates/pipeline.tmpl
Labels: approved, size/XS

#108 fix: don't fail if the trace button is not there
  web/static/pipeline/index.js
Labels: approved, size/S

#109 chore: upgrade dependencies
  go.mod
  go.sum
  web/handlers/logs.go
  web/handlers/logs_live.go
  web/handlers/pipeline.go
  web/handlers/pipelinerun.go
Labels: approved, size/M

#111 feat: status badge for shields.io
  README.md
  web/handlers/router.go
  web/handlers/shields_io.go
Labels: approved, size/M
